name: "Botaffiumeiro"
version: "1.0"
slug: "botaffiumeiro"
description: "Modify Telegram links for affiliate links"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
startup: "services"
boot: "auto"
host_network: true
options:
  bot_token: ""
  excluded_users: ""
  log_level: "INFO"
  amazon_affiliate_id: ""
  awin_publisher_id: ""
  awin_advertisers: ""
  admitad_publisher_id: ""
  admitad_advertisers: ""
  aliexpress_app_key: ""
  aliexpress_app_secret: ""
  aliexpress_tracking_id: ""
  aliexpress_discount_codes: "ğŸ’°2$ off for purchases over 20$:ã€IFPTKOHã€‘\nğŸ’°5$ off for purchases over 50$:ã€IFPT35Dã€‘\nğŸ’°25$ off for purchases over 200$:ã€IFPQDMHã€‘\nğŸ’°50$ off for purchases over 400$:ã€IFP5RINã€‘"
schema:
  bot_token: "str?"
  excluded_users: "str?"
  
