name: Bot Affiumeiro
version: "1.0"
slug: botaffiumeiro
description: "Complemento de Home Assistant para el bot Affiumeiro"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
options:
  path_to_host_data: "/data"
  bot_token: ""
  msg_affiliate_link_modified: "Here is the modified link with our affiliate program:"
  msg_reply_provided_by_user: "Reply provided by"
  excluded_users: "HectorziN,danimart1991"
  log_level: "INFO"
  amazon_affiliate_id: "botaffiumeiro_cofee-21"
  aliexpress_app_key: ""
  aliexpress_app_secret: ""
  aliexpress_tracking_id: ""
  msg_aliexpress_discount: "ğŸ’¥ AliExpress discount codes:\n\n"
  aliexpress_discount_codes: "ğŸ’°2$ off for purchases over 20$:ã€IFPTKOHã€‘\nğŸ’°5$ off for purchases over 50$:ã€IFPT35Dã€‘\nğŸ’°25$ off for purchases over 200$:ã€IFPQDMHã€‘\nğŸ’°50$ off for purchases over 400$:ã€IFP5RINã€‘"
  awin_publisher_id: "1639881"
  awin_advertisers: "pccomponentes.com:20982,leroymerlin.es:20598,aliexpress.com:11640"
  admitad_publisher_id: "2306205"
  admitad_advertisers: "giftmio.com:93fd4vbk6c873a1e3014d68450d763"
schema:
  path_to_host_data: str
  bot_token: str
  msg_affiliate_link_modified: str
  msg_reply_provided_by_user: str
  excluded_users: str?
  log_level: str?
  amazon_affiliate_id: str?
  aliexpress_app_key: str?
  aliexpress_app_secret: str?
  aliexpress_tracking_id: str?
  msg_aliexpress_discount: str?
  aliexpress_discount_codes: str?
  awin_publisher_id: str?
  awin_advertisers: str?
  admitad_publisher_id: str?
  admitad_advertisers: str?
